import { MessageCircle, Search, Send } from "lucide-react";
import { useMemo, useState } from "react";
import { useNetwork } from "../context/NetworkContext";

export default function ChatPage() {
  const { threads, sendMessage } = useNetwork();
  const [selectedId, setSelectedId] = useState<number | null>(threads[0]?.id ?? null);
  const [query, setQuery] = useState(""); const [draft, setDraft] = useState("");
  const visible = useMemo(() => threads.filter((thread) => `${thread.name} ${thread.company}`.toLowerCase().includes(query.toLowerCase())), [threads, query]);
  const active = threads.find((thread) => thread.id === selectedId) ?? visible[0];
  const send = () => { if (active && draft.trim()) { sendMessage(active.id, draft.trim()); setDraft(""); } };
  return <div className="mx-auto grid min-h-[620px] max-w-6xl overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm md:grid-cols-[340px_1fr]"><aside className={`${active ? "hidden md:block" : "block"} border-r border-stone-200 bg-stone-50/60`}><div className="border-b border-stone-200 p-5"><p className="eyebrow">Conversations</p><h1 className="mt-1 text-2xl font-bold text-slate-800">Messages</h1><div className="mt-4 flex items-center gap-2 rounded-xl border border-stone-200 bg-white px-3 py-2"><Search size={17} className="text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search conversations" className="w-full bg-transparent text-sm outline-none"/></div></div><div className="p-2">{visible.map((thread) => <button key={thread.id} onClick={() => setSelectedId(thread.id)} className={`flex w-full items-center gap-3 rounded-2xl p-3 text-left transition ${active?.id === thread.id ? "bg-white shadow-sm" : "hover:bg-white/70"}`}><div className="avatar small">{thread.name[0]}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="truncate font-semibold text-slate-800">{thread.name}</span><span className="text-xs text-slate-400">{thread.time}</span></div><p className="truncate text-sm text-slate-500">{thread.lastMessage}</p></div>{thread.unread > 0 && <span className="notification-dot">{thread.unread}</span>}</button>)}{visible.length === 0 && <p className="p-5 text-sm text-slate-500">No conversations found.</p>}</div></aside>
  <section className={active ? "flex min-h-[620px] flex-col" : "hidden md:flex"}>{active ? <><header className="flex items-center gap-3 border-b border-stone-200 p-5"><button onClick={() => setSelectedId(null)} className="button-quiet px-2 md:hidden">←</button><div className="avatar small">{active.name[0]}</div><div><h2 className="font-semibold text-slate-800">{active.name}</h2><p className="text-xs text-slate-500">{active.role ? `${active.role} · ` : ""}{active.company}</p></div></header><div className="flex-1 space-y-4 overflow-y-auto bg-[#fbfaf7] p-5">{active.messages.length ? active.messages.map((message) => <div key={message.id} className={`flex ${message.sender === "me" ? "justify-end" : "justify-start"}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${message.sender === "me" ? "bg-teal-700 text-white" : "bg-white text-slate-700 shadow-sm"}`}><p>{message.text}</p><span className={`mt-1 block text-[11px] ${message.sender === "me" ? "text-teal-100" : "text-slate-400"}`}>{message.time}</span></div></div>) : <div className="grid h-full place-items-center text-center"><MessageCircle className="text-teal-700"/><p className="mt-3 text-sm text-slate-500">Start a meaningful conversation with {active.name}.</p></div>}</div><footer className="border-t border-stone-200 p-4"><div className="flex gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} placeholder={`Message ${active.name}…`} className="field flex-1"/><button onClick={send} className="button-primary px-4"><Send size={18}/></button></div><p className="mt-2 text-xs text-slate-400">Keep messages respectful and career-focused.</p></footer></> : <div className="m-auto text-center text-slate-500"><MessageCircle className="mx-auto"/><p className="mt-3">Choose a conversation to continue.</p></div>}</section></div>;
}
