import { Bell, Briefcase, GraduationCap, UserCheck } from "lucide-react";
import { useNetwork } from "../context/NetworkContext";

export default function NotificationPage() {
  const { notifications, markAllRead, markRead, acceptRequest, declineRequest } = useNetwork();
  const icon = (type: string) => type === "connection" ? <UserCheck size={20} className="text-teal-700"/> : type === "hiring" ? <Briefcase size={20} className="text-amber-700"/> : type === "mentorship" ? <GraduationCap size={20} className="text-violet-700"/> : <Bell size={20} className="text-slate-600"/>;
  const unread = notifications.filter((notification) => notification.unread).length;
  return <div className="mx-auto max-w-3xl"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="eyebrow">Stay in the loop</p><h1 className="page-title">Notifications</h1><p className="page-subtitle">Your connections, opportunities and community updates in one place.</p></div>{unread > 0 && <button onClick={markAllRead} className="button-quiet shrink-0">Mark all read</button>}</div><div className="card overflow-hidden p-0">{notifications.map((item) => <div key={item.id} onClick={() => markRead(item.id)} className={`flex gap-4 border-b border-stone-100 p-5 last:border-0 ${item.unread ? "bg-teal-50/40" : ""}`}><div className="mt-0.5 rounded-xl bg-white p-2 shadow-sm">{icon(item.type)}</div><div className="min-w-0 flex-1"><p className="font-medium text-slate-700">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.time}</p>{item.action === "connection-request" && item.actorId && <div className="mt-3 flex gap-2"><button onClick={(event) => { event.stopPropagation(); acceptRequest(item.actorId!, "Arjun Patel"); }} className="button-primary py-2 text-sm">Accept</button><button onClick={(event) => { event.stopPropagation(); declineRequest(item.actorId!); }} className="button-quiet py-2 text-sm">Ignore</button></div>}</div>{item.unread && <span className="mt-2 h-2 w-2 rounded-full bg-teal-600"/>}</div>)}</div></div>;
}
